trigger:
- master
############################################################################
pool:
  vmImage: 'ubuntu-latest'
############################################################################
steps:
############################################################################
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
############################################################################
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'test_test1.py'
############################################################################
- script: echo "Hello pipe line M"
  displayName: 'Run a one-line script'
############################################################################
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
############################################################################
- task: SSH@0
  inputs:
    sshEndpoint: 'auser@13.82.64.79'
    runOptions: 'commands'
    commands: 'rm -rf test'
    readyTimeout: '20000'
############################################################################
- script: |
    python -m pip install --upgrade pip
    python3 -m venv test102
    source test102/bin/activate
    pip3 install -r requirements.txt
    pip3 list
    deactivate
  displayName: 'Edit Envv'
############################################################################
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'auser@13.82.64.79'
    contents: 'requirements.txt'
    targetFolder: '/home/auser'
    readyTimeout: '20000'
############################################################################
- task: SSH@0
  inputs:
    sshEndpoint: 'auser@13.82.64.79'
    runOptions: 'commands'
    commands: |
      sudo apt-get install python3-venv
      sudo apt-get install python3-pip
      python3 -m venv test102
      source test102/bin/activate
      pip3 install -r requirements.txt
      pip3 list --format=legacy
      deactivate
    readyTimeout: '20000'